seed: 12345

device: "cuda:0"

defaults:
  - energy: ManyWell
  - model: GFN
  - train: OnPolicy
  - _self_

  # Experiments config file can override the default option.
  - experiment: GFN/OnPolicy/TB+Expl

train:
  trainer:
    _recursive_: false
  device: ${device}

model:
  device: ${device}

eval:
  eval_every_n_epoch: 100
  save_model_every_n_epoch: 1000

  eval_data_size: 2000
  final_eval_data_size: 2000
  plot_sample_size: 2000

hydra:
  run:
    dir: /home/minkyu/diffusion-sampler/results/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep: 
    dir: /home/minkyu/diffusion-sampler/results/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}

logger: "neptune"